version: "1.0"

services:
  nginx-proxy:
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=flask-app:8000
    ports:
      - "80:80"
    depends_on:
      - flask-app
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: /app/start.sh
  flask-app:
    build: ./flask
    restart: always
    volumes:
      - ./constants:/app/constants
      - ./functions:/app/functions
    environment:
      - FLASK_SERVER_PORT=9091
    ports:
      - '8000:8000'
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: gunicorn -w 4 -t 60 -b 0.0.0.0:8000 app:app